### ISSUE TITLE
libpng dependency it's an issue for Mac users

### ISSUE THREAD

**Issue by fernandofranca** [eduardo-costa/web-bundle#6]
The issue with libpng was opened last year and the problems persist (https://github.com/pkrumins/node-png/issues/42).
This problem seems to be well known (https://www.npmjs.com/package/depthcam).
Building it from source didn't solve nothing.

I'd suggest using another png encoder lib than libpng.

Nice job, btw.

**Comment by eduardo-costa** [comment]
Thanks! We will give a look!
@SomeHats

**Comment by SomeHats** [comment]
I wrote this tool on a Mac and had no issue with libpng.

If you're getting the same error as reported in the issue you linked, the problem is that you don't have `pkg-config` installed. There are good instructions for installing it here: https://github.com/Automattic/node-canvas/wiki/installation---osx#pkg-config

You should be able to run `$ pkg-config libpng --libs` and get something along the lines of `-L/usr/local/Cellar/libpng/1.6.15/lib -lpng16`

Let me know if you have any success with this - if it works, we can post the installation instructions to the issue you linked too.

**Comment by fernandofranca** [comment]
Thanks, @SomeHats .
I compiled and installed it as pointed.
`pkg-config libpng --libs` gives me `-L/usr/local/lib -lpng15`.

Still no luck installing node-png module.

**Comment by fernandofranca** [comment]
The following are the errors in node-png module installation:

``````
../src/common.cpp:10:17: error: calling a protected constructor of class
      'v8::HandleScope'
    HandleScope scope;
                ^
/Users/fritz/.node-gyp/0.11.13/deps/v8/include/v8.h:845:13: note:
      declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/common.cpp:11:37: error: no member named 'New' in 'v8::String'
    return Exception::Error(String::New(msg));
                            ~~~~~~~~^
../src/common.cpp:16:17: error: calling a protected constructor of class
      'v8::HandleScope'
    HandleScope scope;
                ^
/Users/fritz/.node-gyp/0.11.13/deps/v8/include/v8.h:845:13: note:
      declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/common.cpp:17:12: error: use of undeclared identifier 'ThrowException';
      did you mean 'ErrorException'?
    return ThrowException(ErrorException(msg));
           ^~~~~~~~~~~~~~
           ErrorException
../src/common.cpp:8:1: note: 'ErrorException' declared here
ErrorException(const char *msg)
^
../src/common.cpp:17:27: error: no viable conversion from 'Handle<v8::Value>' to
      'const char *'
    return ThrowException(ErrorException(msg));
                          ^~~~~~~~~~~~~~~~~~~
../src/common.cpp:8:28: note: passing argument to parameter 'msg' here
ErrorException(const char *msg)
                           ^
5 errors generated.
make: *** [Release/obj.target/png/src/common.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1046:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/fritz/Desktop/shader-test-html/node_modules/web-bundle/node_modules/png
gyp ERR! node -v v0.11.13
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok
npm ERR! png@3.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the png@3.0.3 install script.
npm ERR! This is most likely a problem with the png package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls png
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 14.0.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "web-bundle"
npm ERR! cwd /Users/fritz/Desktop/shader-test-html
npm ERR! node -v v0.11.13
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/fritz/Desktop/shader-test-html/npm-debug.log
npm ERR! not ok code 0```
``````

**Comment by eduardo-costa** [comment]
@SomeHats  @fernandofranca managed to solve it?

**Comment by fernandofranca** [comment]
Nope, I'm stuck with node-png.

**Comment by SomeHats** [comment]
I've been digging in to this a little over the past few days. It seems that `node-png` doesn't support the latest version of nodejs. So a temporary workaround would be to downgrade to node 0.10.x, but it does seem that we need to find an alternative to `node-png`.

The state of node image encoding/decoding libraries is pretty poor at the moment though. Like `node-png`, most seem to not be maintained. I'm going to keep looking and maybe see if I can get `node-png` compiling with newer versions of node.

**Comment by fernandofranca** [comment]
Thanks, @SomeHats !
Tested with node 0.10.32 and all went fine.

**Comment by eduardo-costa** [comment]
@SomeHats @fernandofranca Great work guys!
