### ISSUE TITLE
Fail to extract bundle on android

### ISSUE THREAD

**Issue by memilian** [eduardo-costa/web-bundle#8]
Hello,
I have a bundle that contains 3 files, I extract them successfully on desktop but on android (tested both in chrome and firefox) the binary data is messed up.
eg. instead of reading an entry path as "js/client.js" it reads "ir/clhent/js"
In fact it seems that some pixel values are randomly incremented or decremented by 1
what could possibly cause that ?

**Comment by SomeHats** [comment]
What phone, android version, and browser version is this with?

**Comment by memilian** [comment]
Sorry should have mentionned that. The phone is an HTC Desire 620 with android 4.4.4.
The browsers :
Chrome v 42.0.2311.111
Firefox v 37.0.2

**Comment by memilian** [comment]
It seems that it was caused by the bundle being too large (1.1 Mo). All work fine with a lighter bundle.

**Comment by eduardo-costa** [comment]
How large was the bundle?

width, height and memory plz!

**Comment by memilian** [comment]
The bundle had 3 files in it for a total of  1120 ko.
 Width and height : 608 pixels
